#!/usr/bin/python

import sys
import os
import re
import collections
import argparse

re_separator = re.compile(" - [0-9]")
def commonPrefix(files):
    # TODO
    (v, c) = collections.Counter([re_separator.split(p)[0] for p in files]).most_common(1)[0]
    return c>1 and v or None
    

def processDir(dir, dry_run):
    "Process the files in a directory"
    files = os.listdir(dir)
    prefix = commonPrefix(files)
    if prefix != None:
        for file in (f for f in files if f[:len(prefix)] == prefix):
            newname = file[len(prefix)+3:]
            if dry_run:
                print "renaming: \"%s\" -> \"%s\""%(file, newname)
            if not dry_run:
                os.rename(os.path.join(dir,file), os.path.join(dir,newname))
                

if __name__ == "__main__":

    parser = argparse.ArgumentParser(
        description="Abbreviate the names of Bandcamp-downloaded audio files"
    )
    parser.add_argument("dirs", metavar="dir", nargs="+", help="Directories containing unzipped albums")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    for dir in args.dirs:
        processDir(dir, dry_run=args.dry_run)
